# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'vs2017-win2016'

    steps:
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'assembleRelease'

    # /!\ For the purpose of the tutorial the passwords are visible, use "secret variable" instead like recommended by Microsoft:
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables

    - task: AndroidSigning@3
      inputs:
        apkFiles: '**/*.apk' 
        apksign: true
        apksignerKeystoreFile: 'production.keystore'
        apksignerKeystorePassword: 'keystorepwd'
        apksignerKeystoreAlias: 'key0'
        apksignerKeyPassword: 'aliaspwd'
        apksignerArguments: --out $(Build.SourcesDirectory)/app/build/outputs/apk/release/my-crazy-app.release.apk
        zipalign: true

    - task: CopyFiles@2
      inputs:
        SourceFolder: $(Build.SourcesDirectory)
        contents: '**/*.release.apk' 
        targetFolder: '$(build.artifactStagingDirectory)'
        overWrite: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'vs2017-win2016'

    steps:
    - task: AppCenterTest@1
      inputs:
        appFile: '**/*.apk'
        artifactsDirectory: '$(Build.ArtifactStagingDirectory)/AppCenterTest'
        frameworkOption: 'appium'
        credentialsOption: 'serviceEndpoint'
        localeOption: 'en_US'

    - task: AppCenterDistribute@3
      inputs:
        serverEndpoint: 'AppCenterServiceConnection'
        appSlug: 'salinikrovi-gmail.com/SampleAndroid'
        appFile: '**/*.apk'
        releaseNotesOption: 'input'
        releaseNotesInput: 'New Release v2.0'
        destinationType: 'groups'


